### update
PUT http://localhost:8080/books/7
Content-Type: application/json

{
  "title": "Spring Boot入門 改訂版",
  "author": "山田太郎",
  "volumes": 2,
  "publisher": "技術書出版社",
  "isbn": "9781234567890",
  "genre": "Tech",
  "status": "finished",
  "totalReadingTime": 240
}